version: "3"
services:

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=1q2w3e4r!"
      - "MYSQL_PASSWORD=1q2w3e4r!"

    container_name: mysql
    restart: always

  gomokubot:
    image: gomokubot-discord
    environment:
      - "GOMOKUBOT_B3NZENE_ADDRESS=localhost"
      - "GOMOKUBOT_B3NZENE_PORT=2001"

      - "GOMOKUBOT_DB_URL=r2dbcs:mysql://root:1q2w3e4r!@localhost:3306/gomokubot?autoReconnection=true&useUnicode=true&characterEncoding=UTF-8"

      - "GOMOKUBOT_DISCORD_TOKEN=${GOMOKUBOT_DISCORD_TOKEN}"

    container_name: gomokubot-discord
    restart: always
