version: "3"

services:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - gomokubot-discord
    environment:
      - "POSTGRES_USER=gomokubot"
      - "POSTGRES_DB=gomokubot"
      - "POSTGRES_PASSWORD=acomplexpassword"
    container_name: gomokubot-discord-postgres
    restart: always

  gomokubot:
    image: gomokubot-discord
    ports:
      - "80:80"
    volumes:
      - logs
    networks:
       - gomokubot-discord
    environment:
      - "GOMOKUBOT_KVINE_ADDRESS=localhost"
      - "GOMOKUBOT_KVINE_PORT=2001"

      - "GOMOKUBOT_DB_URL=r2dbc:postgresql://gomokubot:acomplexpassword@localhost/gomokubot"

      - "GOMOKUBOT_DISCORD_TOKEN=${GOMOKUBOT_DISCORD_TOKEN}"
      - "GOMOKUBOT_DISCORD_OFFICIAL_SERVER_ID=${GOMOKUBOT_DISCORD_OFFICIAL_SERVER_ID}"
      - "GOMOKUBOT_DISCORD_ARCHIVE_CHANNEL_ID=${GOMOKUBOT_DISCORD_ARCHIVE_CHANNEL_ID}"
      - "GOMOKUBOT_DISCORD_TESTER_ROLE_ID=${GOMOKUBOT_DISCORD_TESTER_ROLE_ID}"
    container_name: gomokubot-discord-app
    depends_on:
      - database
    restart: always

volumes:
  db:
    driver: local
  logs:
    driver: local

networks:
  gomokubot-discord:
    external: true
